# Interface to use (0.0.0.0 = all interfaces)
interface: 0.0.0.0
# Port to use
port: 80
# An aritrary ascii string to sign sessions etc. Make sure to back it up!
secret: ""
# Debug outputs
debug: false
# Enforce https for full urls?
use_https: false
upload_path: "./uploads"
# Database
database:
  # Database url: 
  url: "postgresql://user:password@host:port/database"
  # Number of connections
  pool_size: 1 # Bjoern (the application server) is single threaded, so it is useless to support more then one connection in production
matomo:
  enabled: false
  url: ""
  site_id: 1
  auth_token: ""
rabbit_mq:
  # RabbitMQ url. Make sure to encode the virtual host: https://pika.readthedocs.io/en/stable/modules/parameters.html#pika.connection.URLParameters
  url: "amqp://user:password@host:port/virtual_host"
  workflow_queue: workflows
workflows:
  local: {}
    # E.g.
    # "Workflow Name":
    #   directory: "/path/to/script/directory"
    #   script: "main_script.nf"
  docker: {}
    # E.g.
    # "Workflow Name":
    #   directory: "/path/to/script/directory"
    #   script: "main_script.nf"
    #   image: "docker/image:name"