interface: 127.0.0.1
port: 3001
secret: "development"
debug: true
use_https: false
database:
  url: postgresql://postgres:developer@127.0.0.1:5433/nf_cloud
  pool_size: 4 # In development mode, more than one connections are supported
rabbit_mq:
  url: "amqp://admin:developer@127.0.0.1:5673/%2f"
workflows:
  "Hello World (Locally)":
    directory: ./test_workflows/hello_world
    script: "main.nf"
    args:
      dynamic:
        inFile:
          type: path
          desc: Single file
          selectable_files: true
          selectable_folders: false
        inFolder:
          type: path
          desc: Single folder
          selectable_files: false
          selectable_folders: true
        inFiles:
          type: paths
          desc: Multiple files
          selectable_files: true
          selectable_folders: false
        inFolders:
          type: paths
          desc: Multiple folder
          selectable_files: false
          selectable_folders: true
        txtFiles:
          type: file-glob
          desc: File "regex", e.g. *.txt
        numberOfNewlines:
          type: number
          desc: Number input 
        singleLineText:
          type: text
          desc: Single line text
        multilineText:
          type: text
          desc: Multiline text
          is_multiline: true
      static:
        outDir:
          type: text
          value: ./
  "Hello World (Docker)":
    directory: ./test_workflows/hello_world
    script: "main.nf"
    nextflow_parameters:
      - "-with-docker"
      - "nfcore/base"
    args:
      dynamic:
        inFile:
          type: path
          desc: Single file
          selectable_files: true
          selectable_folders: false
        inFolder:
          type: path
          desc: Single folder
          selectable_files: false
          selectable_folders: true
        inFiles:
          type: paths
          desc: Multiple files
          selectable_files: true
          selectable_folders: false
        inFolders:
          type: paths
          desc: Multiple folder
          selectable_files: false
          selectable_folders: true
        txtFiles:
          type: file-glob
          desc: File "regex", e.g. *.txt
        numberOfNewlines:
          type: number
          desc: Number input 
        singleLineText:
          type: text
          desc: Single line text
        multilineText:
          type: text
          desc: Multiline text
          is_multiline: true
      static:
        outDir:
          type: text
          value: ./
