# Interface to use (0.0.0.0 = all interfaces)
interface: 0.0.0.0
# Port to use
port: 80
# An aritrary ascii string to sign sessions etc. Make sure to back it up!
secret: ""
# Debug outputs
debug: false
# Enforce https for full urls?
use_https: false
upload_path: "./uploads"
# Database
database:
  # Database url: 
  url: "postgresql://user:password@host:port/database"
  # Number of connections
  pool_size: 1 # Bjoern (the application server) is single threaded, so it is useless to support more then one connection in production
matomo:
  enabled: false
  url: ""
  site_id: 1
  auth_token: ""
rabbit_mq:
  # RabbitMQ url. Make sure to encode the virtual host: https://pika.readthedocs.io/en/stable/modules/parameters.html#pika.connection.URLParameters
  url: "amqp://user:password@host:port/virtual_host"
  # Queue for scheduled projects
  project_workflow_queue: project_workflow
workflows: {}
    # E.g.
    # "Workflow Name":
    #   # This will create the nextflow command: nextflow run -nf-arg1 nf-arg1-value main.nf --arg1 arg1-value ... --arg6 arg6-value --staticArg1 ./
    #   directory: "/path/to/script/directory"
    #   script: "main_script.nf"
    #   # Optional array of directly applied nextflow parameters, e.g. -profile 
    #   nextflow_parameters: 
    #     - "-nf-arg1"
    #     - "nf-arg1-value"
    #   # Script arguments
    #   # Each argument will be added as `--arg1 value --arg2 value` to the nextflow script.
    #   args:
    #     # Dynamic arguments are rendered as formular for users
    #     # If you want to add a default parameter, just add a vaule key to the argument.
    #     dynamic:
    #       # Creates an single file picker
    #       arg1:
    #         type: path
    #         desc: ""
    #         # If true files can be selected
    #         selectable_files: false
    #         # If true folder can be selected
    #         selectable_folders: true
    #       # Creates a select for multiple files, which are added as a
    #       # comma-seperated list.
    #       arg2:
    #         type: paths
    #         desc: ""
    #         # If true files can be selected
    #         selectable_files: false
    #         # If true folder can be selected
    #         selectable_folders: true
    #       # Creates a text box for a file glob or wildcard, e.g. *.txt or *.raws
    #       # The fildcard argument will be prepended with the workdirectory.
    #       arg3:
    #         type: file-glob
    #         desc: ""
    #       # Creates a number input
    #       arg4:
    #         type: number
    #         desc: "" 
    #       # Creates a textbox 
    #       arg5:
    #         type: text
    #         desc: ""
    #       # Creates a multiline text box.
    #       arg6:
    #         type: text
    #         desc: ""
    #         is_multiline: true
    #     static:
    #       # Static arguments are not editable by the user.
    #       staticArg1:
    #         type: text
    #         value: ./