interface: 127.0.0.1
port: 3001
secret: "development"
debug: true
use_https: false
database:
  url: postgresql://postgres:developer@127.0.0.1:5433/nf_cloud
  pool_size: 4 # In development mode, more than one connections are supported
