version: '3'
services:
  psql:
    image: postgres:13
    ports:
      - 127.0.0.1:5433:5432
    environment:
      POSTGRES_PASSWORD: developer
      POSTGRES_DB: nf_cloud
  # backend_1: &backend
  #   build:
  #     context: .
  #     dockerfile: backend.dockerfile
  #   volumes:
  #     # Pass the local config
  #     - ./config.development.yaml:/app/config.development.yaml:ro
  #     - ./config.local.yaml:/app/config.local.yaml:ro
  #   # user: "${UID}:${GID}"
  #   command: ["--environment", "development", "--interface", "0.0.0.0", "--port", "3001"]
  # backend_2: *backend
  # backend_3: *backend
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: frontend.dockerfile
  #   environment:
  #     NF_CLOUD_BACKEND_BASE_URL: http://localhost:8080
  #     NF_CLOUD_FRONTEND_INTERFACE: 0.0.0.0
  #     NF_CLOUD_FRONTEND_PORT: 3000
  #   #user: "${UID}:${GID}"
  #   command: ["--environment", "development"]
  # nginx:
  #   image: nginx:stable-alpine
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./nginx-high-available.conf:/etc/nginx/templates/default.conf.template:ro
  #   depends_on:
  #     - backend_1
  #     - backend_2
  #     - backend_3
  #     - frontend
  #   links:
  #     - backend_1
  #     - backend_2
  #     - backend_3
  #     - frontend