[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nf_cloud_worker"
requires-python = ">=3.9"
version = "1.0.0"
dependencies = [
    "fastapi ~=0.110",
    "mergedeep >=1.3.4, <2",
    "pydantic-settings ~=2.2 ",
    "pika  >=1, <2",
    "requests  >=2, <3",

]

[project.optional-dependencies]
dev = [
    "honcho",
    "pylint"
]